services:
  postgres:
    image: postgres:latest
    container_name: postgreskx
    environment:
      POSTGRES_USER: kontexted
      POSTGRES_PASSWORD: kontexted
      POSTGRES_DB: kontexted
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
volumes:
  pgdata:
