services:
  traefik:
    image: traefik:v3.1
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webapp
  webapp:
    build:
      context: ..
      dockerfile: ./apps/webapp/Dockerfile
    container_name: webapp
    restart: unless-stopped
    environment:
      DATABASE_DIALECT: sqlite
      DATABASE_URL: /data/kontexted.db
      BETTER_AUTH_SECRET: 2f9569d6a7081d4fc978afc430d06b80
      BETTER_AUTH_URL: http://app.localhost
      INVITE_CODE: my-secret-code
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`app.localhost`)"
      - "traefik.http.routers.webapp.entrypoints=web"
      - "traefik.http.services.webapp.loadbalancer.server.port=3000"
    extra_hosts:
      - "app.localhost:host-gateway"
    volumes:
      - sqlite-data:/data

volumes:
  sqlite-data:
